#!/usr/bin/env bash
#
# Build

set -e -o pipefail

: ${PREFIX:=/usr/local}
: ${LIBDIR:="${PREFIX}/lib"}
: ${BINDIR:="${PREFIX}/bin"}

build_install() {
  install -v src/bats-mock.bash "${LIBDIR}"
}

build_test() {
  PATH="${PATH}:${BINDIR}" bats -t test/$([[ -n "$1" ]] && echo "$1.bats")
}

main() {
  : ${1?'Command must be specified'}

  if [[ "${PREFIX:0:1}" != '/' ]]; then
    echo "$(basename $0): PREFIX must be an absolute path" >&2
    exit 1
  fi

  if [[ "${LIBDIR:0:1}" != '/' ]]; then
    echo "$(basename $0): LIBDIR must be an absolute path" >&2
    exit 1
  fi

  "build_$1" "${@:2}"
}

main "$@"
